#+TITLE: I co-wrote a research paper
#+REVEAL_ROOT: ./reveal.js
#+REVEAL_THEME: sky
#+EXPORT_FILE_NAME: index
#+OPTIONS: toc:nil, num:nil, reveal_title_slide:nil
#+REVEAL_HEAD_PREAMBLE: <link rel="stylesheet" href="styles.css"/>

* How to co-write a research paper
Shamama (​/SHa'mämə/​) Zehra \\
February 16, 2018

#+BEGIN_NOTES
  Introduce myself: name, etc
  I’m going to tell you a story today, it’s a little story about how I wrote a research paper, and all the parts you never thought went into publishing a piece of peer-reviewed, scientific literature.
#+END_NOTES

* Background
- I co-wrote a research paper
- We're presenting next week at SIGCSE

* Setting
- Preliminary details: the idea, the collaborators
- Topic: Student Misconceptions of Dynamic Programming
- Method: Interview Students taking CSC373 at UofT
- Old papers: a few, very dry, very long.

#+BEGIN_NOTES
1) I had a few ideas for a research study on student misconceptions. I talked to a prof who I had been a student of and TA-ed with, and he decided to add another professor to the project as well.
2) My partner on the project (Ash) joined, and she had the idea to do research on dynamic Programming
#+END_NOTES

** Reading the Old Research
#ADD GIF here.
#+BEGIN_NOTES
3) So, we finally got started… and we had to read a whole bunch of super new, super boring research papers.
I brought one today for all of us to read! (Screenshot of enstrom, gif of me scrolling through enstrom).
#+END_NOTES

** Ethics Review
- 15 page paper
- who/what/when/where/why/how

#+BEGIN_NOTES
Hammered out details of the process
Basically, We promised our best to not make people cry.
#+END_NOTES

** Interviews
- 14 students, 1 hour each
- 3 - 4 Questions
- Think-aloud technique
- 2 researchers + 1 magic pen
#+BEGIN_NOTES
So we used this pen, it's called the Livescribe Echo, that records voice and the notes taken, and synchronizes both together.
but exporting the file took forever and a damn day!
"paper-based computing platform includes a smartpen, dot paper and software applications"
#+END_NOTES

* Writing the Research Paper!
- Sections: Background, Method, Analysis, Conclusion
- Lots of Analysis!!
- 4 co-writers, about 2 weeks, and lots of coffee
- Many, many, many edits
** Submission

* Feedback
#insert images

* Lessons Learned
- Research is *quite* subjective
- Even peer-reviewed, published research can be very controversial
- Think critically, always

* Questions?
#+BEGIN_NOTES
- That concludes my presentation!
- Thank you for listening.
#+END_NOTES
